# Generated by ChatGPT - adds customer_phone to Order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
