# Generated by ChatGPT - add mpesa_checkout_request_id to Order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_checkout_request_id',
            field=models.CharField(max_length=120, null=True, blank=True),
        ),
    ]
