# Generated by ChatGPT - create Category model and populate from existing Product categories
from django.db import migrations, models


def create_categories(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    Category = apps.get_model('store', 'Category')
    names = Product.objects.values_list('category', flat=True).distinct()
    for n in names:
        if n:
            Category.objects.get_or_create(name=n)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_add_mpesa_checkout_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RunPython(create_categories),
    ]
