# Generated by ChatGPT - migrate Product.category from CharField to FK Category
from django.db import migrations, models


def forwards(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    Category = apps.get_model('store', 'Category')
    # create new FK field 'category_tmp' and populate
    for p in Product.objects.all():
        cat_name = getattr(p, 'category', None)
        if cat_name:
            cat, _ = Category.objects.get_or_create(name=cat_name)
            p.category_tmp_id = cat.id
            p.save()


def backwards(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    for p in Product.objects.all():
        if getattr(p, 'category_tmp_id', None):
            p.category = apps.get_model('store', 'Category').objects.get(id=p.category_tmp_id).name
            p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_add_category_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_tmp',
            field=models.ForeignKey(null=True, blank=True, to='store.category', on_delete=models.SET_NULL),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_tmp',
            new_name='category',
        ),
    ]
