# Generated by Django 6.0.6 on 2026-07-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_category_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('card', 'Card'), ('mpesa', 'M-Pesa')], default='card', max_length=20),
        ),
    ]
